[ClassVersion("1.0.0.0")] 
class Reason
{
    [Read] String Phrase;
    [Read] String Code;
};
[ClassVersion("1.0.0.0"), FriendlyName("EPAntivirusStatus")]
class MSFT_EPAntivirusStatus : OMI_BaseResource
{
    [Key, Description("The name of the Antivirus software.")] string AntivirusName;
    [Write, Description("Specifies the status of the Antivirus agent."), ValueMap{"Running","Stopped"}, Values{"Running","Stopped"}] String Status;
    [Write, Description("Specifies if the Antivirus Software should be installed or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Read, EmbeddedInstance("Reason")] String Reasons[];
};
